package view;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.text.Text;
import model.Customer;
import model.Validator;
import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.ComboBox;

public class RegisterController {
	@FXML
	private Button btnCancel;
	@FXML
	private Button btnSave;
	@FXML
	private TextField txtFirstName;
	@FXML
	private TextField txtLastName;
	@FXML
	private TextField txtAddress;
	@FXML
	private TextField txtCity;
	@FXML
	private ComboBox cbProv;
	@FXML
	private TextField txtPostal;
	@FXML
	private TextField txtHomePhone;
	@FXML
	private TextField txtWorkPhone;
	@FXML
	private TextField txtEmail;
	@FXML
	private ComboBox cbAgent;
	@FXML
	private Text erPostal;
	@FXML
	private Text erEmail;
	@FXML
	private Button btnNext;
	@FXML
	private Button btnPrevious;

	// Event Listener on Button[#btnCancel].onAction
	@FXML
	public void btnCancel_onClick(ActionEvent event) {
		
	}
	// Event Listener on Button[#btnSave].onAction
	@FXML
	public void btnSave_onClick(ActionEvent event) {
		if(validateInput()) {
        	//MainController.selectedCustomer.Copy(editCustomer);
    	}
	}
	// Event Listener on Button[#btnNext].onAction
	@FXML
	public void btnNext_onClick(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnPrevious].onAction
	@FXML
	public void btnPrevious_onClick(ActionEvent event) {
		// TODO Autogenerated
	}
	
	@FXML
	public void cbProv_onSelectChange(ActionEvent event) {
		// TODO Autogenerated
	}
	
	@FXML
	public void cbAgent_onSelectChange(ActionEvent event) {
		// TODO Autogenerated
	}
	
	
	
	//validate input
    private boolean validateInput() {
      	boolean valid = true;
      	String regexPostal="^[A-Za-z]\\d[A-Za-z][ -]?\\d[A-Za-z]\\d$";
      	String regexEmail= "\\w+([-+.']\\w+)*@\\w+([-.]\\w+)*\\.\\w+([-.]\\w+)*";
      	//String regexEmail = "^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$";
      	
      	if(!Validator.IsTxTEmpty(txtFirstName, "First Name"))
      	{
      		valid = false;
      	}
      	if(!Validator.IsTxTEmpty(txtLastName, "Last Name"))
      	{
      		valid = false;
      	}
      	if(!Validator.IsTxTEmpty(txtAddress, "Address"))
      	{
      		valid = false;
      	}
      	if(!Validator.IsTxTEmpty(txtCity, "City"))
      	{
      		valid = false;
      	}
      	if(!Validator.IsTxTEmpty(txtPostal, "Postal"))
      	{
      		valid = false;
      	}
      	if(!Validator.IsTxTEmpty(txtHomePhone, "Phone"))
      	{
      		valid = false;
      	}
      	if(!Validator.IsTxTEmpty(txtEmail, "Email"))
      	{
      		valid = false;
      	}
      	else if(!Validator.IsTxTValid(txtPostal, "Postal", regexPostal)) {
      		valid = false;
      	}
      	else if(!Validator.IsTxTValid(txtEmail, "Email", regexEmail)) {
      		valid = false;
      	}

      		
      	return valid;
      	
      }
}
